webtalk_init -webtalk_dir D:/programming/vhdl_projects/Music_box/Music_box.sim/sim_1/synth/func/xsim/xsim.dir/top_block_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Mar  3 23:10:01 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "03bb9aa1ad415a6dacdda97ac8970514" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "356fedc3e4a64a3f8eb00039806da82b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "38" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8150 Eight-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4100 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "75.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19208_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1227458759 -regid "" -xml D:/programming/vhdl_projects/Music_box/Music_box.sim/sim_1/synth/func/xsim/xsim.dir/top_block_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/programming/vhdl_projects/Music_box/Music_box.sim/sim_1/synth/func/xsim/xsim.dir/top_block_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/programming/vhdl_projects/Music_box/Music_box.sim/sim_1/synth/func/xsim/xsim.dir/top_block_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
